CREATE TABLE IF NOT EXISTS objects(id BIGSERIAL PRIMARY KEY, name TEXT NOT NULL, type TEXT NOT NULL DEFAULT 'housing');
CREATE TABLE IF NOT EXISTS snapshots(id BIGSERIAL PRIMARY KEY, object_id BIGINT NOT NULL REFERENCES objects(id), filename TEXT NOT NULL, src TEXT NOT NULL, captured_at DATE NOT NULL, status TEXT NOT NULL DEFAULT 'new', width INTEGER NOT NULL, height INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS detections(id BIGSERIAL PRIMARY KEY, snapshot_id BIGINT NOT NULL REFERENCES snapshots(id), model TEXT NOT NULL, label TEXT NOT NULL, score DOUBLE PRECISION NOT NULL, x1 DOUBLE PRECISION NOT NULL, y1 DOUBLE PRECISION NOT NULL, x2 DOUBLE PRECISION NOT NULL, y2 DOUBLE PRECISION NOT NULL);
ALTER TABLE detections ADD COLUMN IF NOT EXISTS verdict TEXT NOT NULL DEFAULT '';
CREATE TABLE IF NOT EXISTS stages(id BIGSERIAL PRIMARY KEY, object_id BIGINT NOT NULL REFERENCES objects(id), position INTEGER NOT NULL, kind TEXT NOT NULL, name TEXT NOT NULL, date_from DATE NOT NULL, date_to DATE NOT NULL, status TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS warnings(id BIGSERIAL PRIMARY KEY, object_id BIGINT NOT NULL REFERENCES objects(id), snapshot_id BIGINT NOT NULL REFERENCES snapshots(id), rule TEXT NOT NULL, title TEXT NOT NULL, body TEXT NOT NULL, why TEXT NOT NULL, source TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'open', severity TEXT NOT NULL DEFAULT 'violation');
CREATE TABLE IF NOT EXISTS object_comments(id BIGSERIAL PRIMARY KEY, object_id BIGINT NOT NULL REFERENCES objects(id), body TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS object_events(id BIGSERIAL PRIMARY KEY, object_id BIGINT NOT NULL REFERENCES objects(id), stage_id BIGINT REFERENCES stages(id), snapshot_id BIGINT REFERENCES snapshots(id), event_type TEXT NOT NULL DEFAULT 'human', title TEXT NOT NULL, body TEXT NOT NULL DEFAULT '', event_date DATE NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS catalog(id BIGSERIAL PRIMARY KEY, code TEXT NOT NULL, name TEXT NOT NULL, applies TEXT NOT NULL);
﻿-- BuildWatch production additions. Apply with Alembic or your migration runner.
CREATE TABLE IF NOT EXISTS users (id BIGSERIAL PRIMARY KEY, email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'viewer', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS audit_log (id BIGSERIAL PRIMARY KEY, user_id BIGINT REFERENCES users(id), action TEXT NOT NULL, entity TEXT, entity_id BIGINT, details JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS detection_jobs (id BIGSERIAL PRIMARY KEY, snapshot_id BIGINT NOT NULL UNIQUE REFERENCES snapshots(id), model TEXT NOT NULL DEFAULT 'yolo_world', status TEXT NOT NULL DEFAULT 'queued', attempts INTEGER NOT NULL DEFAULT 0, error TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), started_at TIMESTAMPTZ, finished_at TIMESTAMPTZ);
ALTER TABLE detection_jobs ADD COLUMN IF NOT EXISTS model TEXT NOT NULL DEFAULT 'yolo_world';
CREATE INDEX IF NOT EXISTS idx_jobs_status_created ON detection_jobs(status, created_at);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_log(created_at);
ALTER TABLE objects ADD COLUMN IF NOT EXISTS district TEXT NOT NULL DEFAULT '';
ALTER TABLE objects ADD COLUMN IF NOT EXISTS address TEXT NOT NULL DEFAULT '';
ALTER TABLE objects ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '';
CREATE TABLE IF NOT EXISTS assistant_proposals (
  id TEXT PRIMARY KEY,
  object_id BIGINT NOT NULL REFERENCES objects(id),
  stage_id BIGINT NOT NULL REFERENCES stages(id),
  old_from TEXT NOT NULL,
  old_to TEXT NOT NULL,
  new_from TEXT NOT NULL,
  new_to TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  expires_at TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
